{{- if .Values.admin.autoscaling.enabled }}
apiVersion: {{ include "hoppscotch.apiVersion.autoscaling" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hoppscotch.fullname" (dict "context" . "name" .Values.admin.name) }}
  labels:
    {{- include "hoppscotch.labels" (dict "context" . "name" .Values.admin.name) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hoppscotch.fullname" (dict "context" . "name" .Values.admin.name)  }}
  minReplicas: {{ .Values.admin.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.admin.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.admin.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        {{- if eq (include "hoppscotch.apiVersion.autoscaling" $) "autoscaling/v2beta1" }}
        targetAverageUtilization: {{ .Values.admin.autoscaling.targetCPUUtilizationPercentage }}
        {{- else }}
        target:
          type: Utilization 
          averageUtilization: {{ .Values.admin.autoscaling.targetCPUUtilizationPercentage }}
        {{- end  }}
    {{- end }}
    {{- if .Values.admin.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        {{- if eq (include "hoppscotch.apiVersion.autoscaling" $) "autoscaling/v2beta1" }}
        targetAverageUtilization: {{ .Values.admin.autoscaling.targetCPUUtilizationPercentage }}
        {{- else }}
        target:
          type: Utilization 
          averageUtilization: {{ .Values.admin.autoscaling.targetMemoryUtilizationPercentage }}
        {{- end  }}
    {{- end }}
{{- end }}
