{{- if .Values.global.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hoppscotch.serviceAccountName" . }}
  labels:
    {{- include "hoppscotch.labels"  (dict "context" . "name" "global") | nindent 4 }}
  {{- range $key, $value := .Values.global.serviceAccount.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- with .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
