name: Update Release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  build-and-push-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: hoppscotch/hoppscotch
          ref: main

      - name: Fetch Latest Release Tag
        id: fetch_tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag=$(gh release view -R hoppscotch/hoppscotch --json tagName | jq -r .tagName)
          echo "tag=${tag}" >> $GITHUB_OUTPUT

      # This should not be needed
      - name: copy .env
        run: cp .env.example .env

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish Docker image (Backend)
        uses: docker/build-push-action@v5
        with:
          file: packages/hoppscotch-backend/Dockerfile
          context: .
          target: prod
          push: true
          tags: ghcr.io/wdaan/hoppscotch-backend:${{ steps.fetch_tag.outputs.tag }}

      - name: Build and publish Docker image (web)
        uses: docker/build-push-action@v5
        with:
          file: packages/hoppscotch-selfhost-web/Dockerfile
          context: .
          push: true
          tags: ghcr.io/wdaan/hoppscotch-web:${{ steps.fetch_tag.outputs.tag }}
      
      - name: Build and publish Docker image (Admin)
        uses: docker/build-push-action@v5
        with:
          file: packages/hoppscotch-sh-admin/Dockerfile
          context: .
          push: true
          tags: ghcr.io/wdaan/hoppscotch-admin:${{ steps.fetch_tag.outputs.tag }}

  update-chart-versions:
    runs-on: ubuntu-latest
    needs: [build-and-push-containers]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch Latest Release Tag
        id: fetch_tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag=$(gh release view -R hoppscotch/hoppscotch --json tagName | jq -r .tagName)
          echo "tag=${tag}" >> $GITHUB_OUTPUT
     
      - name: Update Chart Versions
        id: update_chart
        run: |
          tag="${{ steps.fetch_tag.outputs.tag }}"
          # set current app version
          yq e ".appVersion = \"${tag}\"" -i charts/hoppscotch/Chart.yaml
          # bump current chart MINOR version
          yq e '.version' charts/hoppscotch/Chart.yaml | awk -F. '{ print $1,$2+1,$3 }' OFS=. | xargs -I{} yq e '.version = "{}"' -i charts/hoppscotch/Chart.yaml

      - name: Open PR
        env:
          GIT_AUTHOR_NAME: hoppscotch-bot
          GIT_AUTHOR_EMAIL: dev@hoppscotch.io
          GIT_COMMITTER_NAME: hoppscotch-bot
          GIT_COMMITTER_EMAIL: dev@hoppscotch.io
          GH_TOKEN: ${{ github.token }}
        run: |
          tag="${{ steps.fetch_tag.outputs.tag }}"
          git checkout -b "update/${tag}"
          git add charts/hoppscotch/Chart.yaml
          git commit -m "feat: update hoppscotch version to release ${tag}"
          git push origin "update/${tag}"
          gh pr create --title "feat: update hoppscotch version to release ${tag}" \
            --body "Updating chart to hoppscotch release [${tag}](https://github.com/hoppscotch-io/hoppscotch/releases/tag/${tag})."
